apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-vault.fullname" . }}
  labels:
    {{- include "dotnet-vault.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "VaultSecrets": {
        {{` {{- with secret "secrets/data/services/dotnet" }}
          "userName": "{{ .Data.data.username }}",
          "password": "{{ .Data.data.password }}"
        {{- end }} `}}
      }
    }
