apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-vault.fullname" . }}
  labels:
    {{- include "dotnet-vault.labels" . | nindent 4 }}
data:
  # see https://github.com/hashicorp/vault-k8s/pull/222
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "VaultSecrets": {
        {{` {{ with secret "secrets/data/services/dotnet" }}
          "userName": "{{ .Data.data.username }}",
          "password": "{{ .Data.data.password }}"
        {{ end }} `}}
      }
    }
