apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-vault.fullname" . }}
  labels:
    {{- include "dotnet-vault.labels" . | nindent 4 }}
data:
  config-init.hcl: |
      "auto_auth" = {
        "method" = {
          "config" = {
            "role" = "service"
          }
          "type" = "kubernetes"
        }
        "sink" = {
          "config" = {
            "path" = "/home/vault/.token"
          }
           "type" = "file"
        }
      }
      "exit_after_auth" = true
      "pid_file" = "/home/vault/.pid"

      "template" = {
        "contents" = "{{` {{ with secret \"secrets/services/dotnet\" }}{{ .Data.data.username }}:{{ .Data.data.password }}{{ end }} `}}"
        "destination" = "/vault/secrets/app.settings"
      }

      "vault" = {
        "address" = "http://vault.default.svc:8200"
      }
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "service"
        }
        "type" = "kubernetes"
      }
      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }
         "type" = "file"
      }
    }
    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{` {{ with secret \"secrets/services/dotnet\" }}{{ .Data.data.username }}:{{ .Data.data.password }}{{ end }} `}}"
      "destination" = "/vault/secrets/credentials"
    }

    "vault" = {
      "address" = "http://vault.default.svc:8200"
    }
